project:
  type: book
  output-dir: docs

book:
  title: "Con-Gen-2023"
  author: "Eric C. Anderson"
  date: "8/28/2023"
  chapters:
    - index.qmd
    - probinf.qmd
    - snakemake.qmd
    - references.qmd
  sidebar: 
    logo: quarto-static/fisheries_header_logo_jul2019.png
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

